### PR TITLE
Include a divider when infinite scrolling

### LINKED ISSUE #83: No dividers when infinite scrolling
### 📝 Describe the bug

No dividers appear when new posts are loaded in infinite scroll

### 🔄 To Reproduce

1. Scroll in the news list
2. No dividers should appear for loaded news posts

### 📷 Screenshots

image  
Which should look like
image

### 💡 Additional context

_No response_

### PR DESCRIPTION
**Pull request by GAsplund**
Closes #83

### CODE REVIEW

**Review by simon-wg — COMMENTED** [review]
I would consider importing Fragment from 'react' rather than importing React and using React.Fragment. 

Otherwise lgtm.

**Comment by GAsplund** [comment]
I'm honestly unsure if it should be `React.Fragment` or just `Fragment`. We've been using `React.Fragment` elsewhere in the code, and the examples in the React docs uses that too. The only reason I could see why would be to make it clear that it's not an element of its own.

**Comment by simon-wg** [comment]
From what I can see in the most recent [documentation](https://react.dev/reference/react/Fragment) \<Fragment\> is used alone. 

I was mostly worried about eventual performance downsides, but after reading up om it, it mostly seems to be a readability issue.

**Review by Oscariremma — APPROVED** [review]
Given that the react import thing discuses earlier seams to be fine. LGTM

**Pull request merged**
