### PR TITLE
Better news notifier parsing

### LINKED ISSUE #138: File paths in slack notifications are still broken
### 📝 Describe the bug

When you post news with file uploads to slack the don't add the website root path before the local route.

### 🔄 To Reproduce

1. Post a slack news post with a file upload.

### 📷 Screenshots

_No response_

### 💡 Additional context

_No response_

### PR DESCRIPTION
**Pull request by GAsplund**
# Key features
- Parse to `rich_text` instead of `mrkdwn` (this is [strongly recommended](https://api.slack.com/reference/block-kit/blocks#rich_text) by Slack)
- Use parsed HTML from `marked` to make content more in line with the content shown on the page
  - Note that `mack` also converts to intermediary HTML, so this has largely no real difference in how it is parsed before being converted into block kit
- Displays the article title in notifiers
- Uses base URL for images and links
- Closes #138 

# Known issues
- Some hacks are needed to be done to prevent empty objects to be sent to Slack
  - This will hopefully get fixed in a later release of `html-to-slack` - See https://github.com/matteodf/html-to-slack/issues/8

### CODE REVIEW

**Comment by simon-wg** [comment]
I'll take a look at this asap. Do you think this will fix issue #138 ?

For some reason #135 didn't work.

**Review by simon-wg — COMMENTED** [review]
Lgtm.

**Review by simon-wg — APPROVED** [review]

**Comment by GAsplund** [comment]
> I'll take a look at this asap. Do you think this will fix issue #138 ?
> 
> For some reason #135 didn't work.

I've tested and it should work, at least better than the (more) hacky solution we had before

**Comment by simon-wg** [comment]
Yep after reading through the code it seems like it should finally fix that pesky bug!

**Pull request merged**
