### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by GAsplund**
Contains translations for all pages and components.

Also fixes an issue where the "create" button on division pages was visible for everyone.

### CODE REVIEW

**Review by simon-wg — COMMENTED** [review]
12.31 ./src/app/[locale]/layout.tsx
12.31 Module not found: Can't resolve 'nextjs-toploader'

LGTM, just needs nextjs-toploader added to the package.json I think

**Comment by GAsplund** [comment]
Oh, woops. That was there from some experimentation I was doing. Will remove

**Review by simon-wg — APPROVED** [review]
LGTM

**Review by Oscariremma — APPROVED** [review]
LGTM too!

**Pull request merged**
