### PR TITLE
Should fix the news post links not working properly in markdown.

### PR DESCRIPTION
**Pull request by simon-wg**

### CODE REVIEW

**Comment by GAsplund** [comment]
While this is a solution, it should probably be implemented the same way [NotifyService](https://github.com/cthit/chalmers.it/blob/d0858d8a9142e0ec57f93918dea93f810662017a/src/services/notifyService.ts#L120) does for images.

**Comment by simon-wg** [comment]
That's fair, I'll look into it.

**Comment by simon-wg** [comment]
The only thing I'm unsure of is what happens if inserting the base url would exceed the 3000 character limit of the block, and how to eventually split it up if that happens.

**Comment by simon-wg** [comment]
Although maybe that's a non-issue, I don't see anything handling that right now either way.

**Review by GAsplund — APPROVED** [review]
This works for now. We should probably look into parsing and serializing contents better down the line.

**Pull request merged**
