### PR TITLE
navbar restructure

### PR DESCRIPTION
**Pull request by epicreach**
move around links and added som words to the .json files

### CODE REVIEW

**Review by Zazmuz — APPROVED** [review]
Looking good, il ike it

**Review by simon-wg — APPROVED** [review]
lgtm

**Comment by GAsplund** [comment]
Any screenshots?

**Comment by simon-wg** [comment]
:skull:

**Comment by epicreach** [comment]
> Any screenshots?

🤓

**Comment by GAsplund** [comment]
> > Any screenshots?
> 
> 🤓

🤡

**Comment by epicreach** [comment]
> > > Any screenshots?
> > 
> > 
> > 🤓
> 
> 🤡

👴

**Comment by GAsplund** [comment]
> > > > Any screenshots?
> > > 
> > > 
> > > 🤓
> > 
> > 
> > 🤡
> 
> 👴

😭

**Pull request merged**
