### PR TITLE
Fix for calendar

### PR DESCRIPTION
**Pull request by simon-wg**

### CODE REVIEW

**Comment by simon-wg** [comment]
Current version:
image

New version:
image

**Comment by GAsplund** [comment]
Good idea. I would like to have the possibility somewhere of making it not wrap though (I don't think "Skapa nyhet" should ever wrap for example, that might've been the main reason it was implemented). Maybe no wrapping should be the rule and wrapping the exception?

Also, I would set max-width to 100% instead to make sure that we don't get mega-wide buttons with not much text.

Also that's a chonky button 💪

**Comment by simon-wg** [comment]
That's true! I'll change some things around.

**Comment by simon-wg** [comment]
image

**Comment by simon-wg** [comment]
Personally I think it's unnecessary to specify that google calendar is used, so this is the easiest way to solve the wrapping without thiccccening the button.

**Comment by GAsplund** [comment]
Looks good, although I'd be cautious about using flex for content panes, as that applies for every single location it's used on the site (basically everywhere) and may have unintended side-effects.

**Review by ViktorYeet — APPROVED** [review]
lgmt

**Pull request merged**
